### ISSUE TITLE
Success Install Report on OSCOO 256GB ON800 M.2 2280 NGFF SSD

### ISSUE THREAD

**Issue by omac777** [xerolinux/xero_iso#10]
The XeroLinux Calamares installer is slick.
I love the wizard to go to the next and previous steps.

In fact when I tried the auto-partition of device, it automatically allocated 300MB for the /boot/efi which I found small so I went and clicked "back" and gave /boot/efi 2048 MiB instead, the remaining to / as btrfs except for a 7.5 GB of swap.

I started at 1713hrs EST.  It finished the install at 1718hrs EST(5 minutes install) and with a BIG AND NICE restart button! 
Excellent work!

After my first reboot into the installed system, I was welcomed with another dialog to update the mirrorlist, update the software, and install drivers.  Excellent work.  I was able to install the appropriate drivers for my legacy AMD gpu with no issues.

I wish the XeroLinux team health, happiness and prosperity.

**Comment by TechXero** [comment]
Thanks and am glad it all works. Enjoy it my friend.
