### ISSUE TITLE
How to modify?

### ISSUE THREAD

**Issue by ajaysfuckery** [xerolinux/xero_iso#2]
In the README file it says to modify. How would i do this?

**Comment by TechXero** [comment]
What do you want to do exactly? You want to create your own Distro? Cloning this repo and building will result in my Distro. 

To learn how to modify need to watch videos read Wiki etc... I can point you to ArcoLinux ALCI/CARLI projects that's how I started...

**Comment by ajaysfuckery** [comment]
At the moment in general I am trying to create a custom arch iso to become familiar with the process of building a custom distro. Could you point me to ArcoLinux ALCI/CARLI projects? That would be of great help.
