### ISSUE TITLE
Installer failure

### ISSUE THREAD

**Issue by jacksoneyton** [xerolinux/xero_iso#3]
Attempts to install are met with the following. System had a running linux distro prior, I have another machine of the exact same specs running xerolinux flawless. One difference is the TP-Link wireless N USB adapter in the one that fails here. Error copied:
[https://termbin.com/nw9v](https://termbin.com/nw9v)

**Comment by Joarell** [comment]
Hi there!
First of all, congrats for all you people involved on this project!
I've been try to install this amazing distro, but... I was not able to.
Could you please give me some help?

![imagem_2021-11-16_004503](https://user-images.githubusercontent.com/42722369/141892081-61fab60d-7e0d-4daf-a71f-6c56dc1583fa.png)

**Comment by TechXero** [comment]
That's am Internet issue it lost connection during setup. It happens on slower connections.
