### ISSUE TITLE
Broken terminal on resizing.

### ISSUE THREAD

**Issue by RashiqAzhan** [xerolinux/xero_iso#5]
The video shows the issue. Any ideas to fix this?

![Broken Terminal](https://user-images.githubusercontent.com/7370540/143248847-b4eb7074-1af0-468d-be74-38b22d771a99.gif)

**Comment by TechXero** [comment]
Unfortunately I have no clue. I think it's either related to neofetch not being well rendered in zsh or a zsh issue I got no clue it sometimes happens to me as well could never find the solution. I will update this once I find one..

**Comment by RashiqAzhan** [comment]
Thank you for the quick reply. I'm leaning toward a zsh issue since it happens on an empty terminal as well.

![image](https://user-images.githubusercontent.com/7370540/143259004-bce462ce-97c2-485f-8c4a-961f3cce92ff.png)

**Comment by TechXero** [comment]
If it doesn't happen when you use Bash that narrows it down to ZSH.. Try going to Settings > Edit Current Profile > set it to /bin/bash see if it still happens if it does and you prefer ZSH then switch it back to /bin/zsh....
